Repository bowe-td/react-web-example, pull requests merged in 2020-09, with the labels that each got.

#6 feat(absolute-import): adding absolute import and fixing imports on f…
  jsconfig.json
  package.json
  src/App.jsx
  src/components/Route/index.jsx
  src/pages/Login/index.jsx
  src/providers/AppProvider.jsx
  src/providers/AuthProvider.jsx
  yarn.lock
Labels: enhancement

#12 Implement partial Package by feature folder organization.
  .eslintrc.json
  jsconfig.json
  package.json
  src/App.test.js
  src/App.tsx
  src/commons/components/Button/__tests__/index.spec.ts
  src/commons/components/Button/index.tsx
  src/commons/components/Button/styled.js
  src/commons/components/Route/index.tsx
  src/commons/components/index.ts
  src/commons/helpers/__tests__/getStatus.spec.ts
  src/commons/helpers/getStatus.ts
  src/commons/providers/AppProvider.tsx
  src/commons/providers/AuthProvider.tsx
  src/commons/services/api.ts
  src/commons/services/auth.ts
  src/commons/styles/global.ts
  src/commons/styles/theme.ts
  src/components/Button/index.jsx
  src/index.tsx
  src/modules/Auth/ForgotPassword.tsx
  src/modules/Auth/Login.tsx
  src/modules/Auth/SignUp.tsx
  src/modules/Auth/index.jsx
  src/modules/Home/index.tsx
  src/modules/Home/styles.js
  src/modules/index.tsx
  src/pages/index.js
  src/providers/AuthProvider.jsx
  src/react-app-env.d.ts
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: dependencies, feature

#15 Feature/i18n
  package.json
  prettier.config.js
  public/locales/pt-BR/auth.json
  public/locales/pt-BR/commons.json
  public/locales/pt-BR/home.json
  src/commons/components/Button/index.tsx
  src/i18n.ts
  src/index.tsx
  src/modules/Auth/ForgotPassword.tsx
  src/modules/Auth/Login.tsx
  src/modules/Auth/SignUp.tsx
  src/modules/Auth/index.jsx
  src/modules/Home/index.tsx
  src/modules/index.tsx
  yarn.lock
Labels: feature
